/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Preview = {
  barTitle?: string;
  barChip?: string;
};

export type RoadmapItem = {
  _id: string;
  _type: "roadmapItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  column?: "now" | "next" | "later";
  category?: "community" | "training" | "app" | "payments" | "coach";
  title?: string;
  desc?: string;
  eta?: string;
  votes?: number;
  order?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Guide = {
  _id: string;
  _type: "guide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?:
    | "getting-started"
    | "branded-app"
    | "programming"
    | "community"
    | "payments"
    | "retention";
  level?: "Beginner" | "Intermediate" | "Advanced";
  readMin?: number;
  updatedAt?: string;
  lead?: string;
  popular?: boolean;
  order?: number;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & GuideCallout)
    | ({
        _key: string;
      } & Checklist)
    | ({
        _key: string;
      } & GuideSteps)
    | ({
        _key: string;
      } & GuideFaq)
    | ({
        _key: string;
      } & GuideVideo)
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: "stories" | "retention" | "training" | "business" | "product";
  excerpt?: string;
  lead?: string;
  publishedAt?: string;
  readMin?: number;
  featured?: boolean;
  pick?: boolean;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Callout)
    | ({
        _key: string;
      } & Pullquote)
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  seo?: Seo;
};

export type PricingFeatures = {
  _id: string;
  _type: "pricingFeatures";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  included?: boolean;
  language?: string;
};

export type PricingFeaturesReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pricingFeatures";
};

export type Pricing = {
  _id: string;
  _type: "pricing";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  priceMonthly?: number;
  priceYearly?: number;
  features?: Array<
    {
      _key: string;
    } & PricingFeaturesReference
  >;
  highlighted?: boolean;
  language?: string;
};

export type AffiliateSettings = {
  _id: string;
  _type: "affiliateSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  rate?: number;
  sliderMin?: number;
  sliderMax?: number;
  sliderDefault?: number;
  ticks?: Array<number>;
  eur?: {
    avg?: number;
    lo?: number;
    hi?: number;
  };
  usd?: {
    avg?: number;
    lo?: number;
    hi?: number;
  };
};

export type PricingPlans = {
  _id: string;
  _type: "pricingPlans";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tiers?: Array<
    {
      _key: string;
    } & PricingTier
  >;
  betaDiscountPct?: number;
  feesFree?: PlanFees;
  feesClub?: PlanFees;
};

export type PlanFees = {
  _type: "planFees";
  stripePctEur?: number;
  stripeFixedEur?: number;
  stripePctUsd?: number;
  stripeFixedUsd?: number;
  jimmyPct?: number;
};

export type ChangelogChange = {
  _type: "changelogChange";
  type?: "new" | "improved" | "fixed";
  text?: string;
};

export type FeatureCap = {
  _type: "featureCap";
  iconKey?: string;
  title?: string;
  desc?: string;
};

export type GuideVideo = {
  _type: "guideVideo";
  label?: string;
  duration?: string;
  url?: string;
};

export type GuideFaq = {
  _type: "guideFaq";
  items?: Array<{
    q?: string;
    a?: string;
    _type: "guideFaqItem";
    _key: string;
  }>;
};

export type GuideSteps = {
  _type: "guideSteps";
  items?: Array<{
    title?: string;
    body?: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal" | "h3";
          listItem?: "bullet";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | ({
          _key: string;
        } & GuideCallout)
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: "image";
          _key: string;
        }
    >;
    _type: "stepItem";
    _key: string;
  }>;
};

export type Checklist = {
  _type: "checklist";
  items?: Array<string>;
};

export type GuideCallout = {
  _type: "guideCallout";
  tone?: "note" | "tip" | "warn" | "success";
  label?: string;
  text?: string;
};

export type Pullquote = {
  _type: "pullquote";
  text?: string;
  cite?: string;
};

export type Callout = {
  _type: "callout";
  tone?: "spark" | "check";
  label?: string;
  text?: string;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: string;
};

export type TeamStat = {
  _type: "teamStat";
  num?: string;
  heading?: string;
  body?: string;
};

export type TeamMember = {
  _type: "teamMember";
  name?: string;
  role?: string;
  bio?: string;
  location?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type PricingAddon = {
  _type: "pricingAddon";
  name?: string;
  price?: string;
};

export type PricingTier = {
  _type: "pricingTier";
  clients?: string;
  priceEur?: number;
  priceUsd?: number;
};

export type PlatformStep = {
  _type: "platformStep";
  id?: string;
  name?: string;
  tagline?: string;
  tags?: Array<string>;
  preview?: Preview;
};

export type FeatureTab = {
  _type: "featureTab";
  id?: string;
  label?: string;
  title?: string;
  subtitle?: string;
  tags?: Array<string>;
};

export type PortableTextBlock = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SocialLink = {
  _type: "socialLink";
  platform?:
    | "twitter"
    | "instagram"
    | "facebook"
    | "linkedin"
    | "youtube"
    | "tiktok";
  url?: string;
};

export type NavMegaItem = {
  _type: "navMegaItem";
  key?: string;
  title?: string;
  subtitle?: string;
  href?: string;
};

export type NavItem = {
  _type: "navItem";
  label?: string;
  href?: string;
  external?: boolean;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type PricingPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "pricingPage";
};

export type AffiliatePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "affiliatePage";
};

export type NavigationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "navigation";
};

export type FooterReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "footer";
};

export type SiteSettingsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "siteSettings";
};

export type FeatureReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "feature";
};

export type ChangelogReleaseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "changelogRelease";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | HomePageReference
    | PricingPageReference
    | AffiliatePageReference
    | NavigationReference
    | FooterReference
    | SiteSettingsReference
    | FeatureReference
    | ChangelogReleaseReference;
};

export type ChangelogRelease = {
  _id: string;
  _type: "changelogRelease";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  version?: string;
  date?: string;
  title?: string;
  lead?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  changes?: Array<
    {
      _key: string;
    } & ChangelogChange
  >;
};

export type Feature = {
  _id: string;
  _type: "feature";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  name?: string;
  slug?: Slug;
  audience?: "For Coaches" | "For Members";
  order?: number;
  sub?: string;
  iconKey?: string;
  demoKey?: string;
  title?: {
    prefix?: string;
    accent?: string;
    suffix?: string;
  };
  highlight?: {
    prefix?: string;
    accent?: string;
  };
  highlightSub?: string;
  lead?: string;
  tags?: Array<string>;
  capsTitle?: string;
  caps?: Array<
    {
      _key: string;
    } & FeatureCap
  >;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  siteDescription?: string;
  seo?: Seo;
  notFound?: {
    eyebrow?: string;
    title?: string;
    lead?: string;
    ctaPrimary?: string;
    ctaSecondary?: string;
  };
  language?: string;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  taglinePrefix?: string;
  taglineEmphasis?: string;
  productHeading?: string;
  productLinks?: Array<
    {
      _key: string;
    } & NavItem
  >;
  companyHeading?: string;
  companyLinks?: Array<
    {
      _key: string;
    } & NavItem
  >;
  legalHeading?: string;
  legalLinks?: Array<
    {
      _key: string;
    } & NavItem
  >;
  copy?: string;
  language?: string;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  featuresLabel?: string;
  featuresForCoaches?: string;
  featuresForMembers?: string;
  featuresItems?: Array<
    {
      _key: string;
    } & NavMegaItem
  >;
  featuresCta?: {
    label?: string;
    title?: string;
    body?: string;
    btn?: string;
  };
  resourcesLabel?: string;
  resourcesContent?: string;
  resourcesCommunity?: string;
  resourcesItems?: Array<
    {
      _key: string;
    } & NavMegaItem
  >;
  pricing?: string;
  affiliate?: string;
  newBadge?: string;
  login?: string;
  getStarted?: string;
  getStartedShort?: string;
  openMenu?: string;
  close?: string;
  menu?: string;
  language?: string;
};

export type AffiliatePage = {
  _id: string;
  _type: "affiliatePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  language?: string;
  hero?: {
    socialProof?: string;
    eyebrow?: string;
    headlinePrefix?: string;
    headlineAccent?: string;
    headlineSuffix?: string;
    subtitle?: string;
    ctaPrimary?: string;
    ctaSecondary?: string;
  };
  calc?: {
    title?: string;
    helper?: string;
    coachesSuffix?: string;
    perMo?: string;
    estimateLabel?: string;
    recurringBadge?: string;
    monthlyLabel?: string;
    perYearTemplate?: string;
    basisLabel?: string;
    basisRangePrefix?: string;
    basisRangeSuffix?: string;
    footnote?: string;
    referralsLabel?: string;
    perMonthLabel?: string;
    perMonthTip?: string;
    perYearLabel?: string;
    perYearTip?: string;
    cta?: string;
    note?: string;
  };
  how?: {
    eyebrow?: string;
    title?: string;
    subtitle?: string;
    steps?: Array<{
      label?: string;
      name?: string;
      tagline?: string;
      _type: "step";
      _key: string;
    }>;
    labels?: {
      partnerBarTitle?: string;
      freeBadge?: string;
      accountName?: string;
      accountRole?: string;
      approved?: string;
      referralLinkLabel?: string;
      copy?: string;
      copied?: string;
      copiedToast?: string;
      tagsStep1?: Array<string>;
      shareBarTitle?: string;
      liveBadge?: string;
      linkClicksLabel?: string;
      clicksBadge?: string;
      channels?: Array<{
        name?: string;
        source?: string;
        _type: "channel";
        _key: string;
      }>;
      tagsStep2?: Array<string>;
      commissionsBarTitle?: string;
      monthBadge?: string;
      availableLabel?: string;
      withdraw?: string;
      newPaymentTemplate?: string;
      completed?: string;
      commissionTag?: string;
      tagsStep3?: Array<string>;
    };
  };
  why?: {
    eyebrow?: string;
    title?: string;
    cards?: Array<{
      title?: string;
      body?: string;
      _type: "card";
      _key: string;
    }>;
  };
  who?: {
    title?: string;
    subtitle?: string;
    items?: Array<{
      title?: string;
      sub?: string;
      _type: "item";
      _key: string;
    }>;
  };
  faq?: {
    eyebrow?: string;
    title?: string;
    items?: Array<
      {
        _key: string;
      } & FaqItem
    >;
    footNote?: string;
    footLink?: string;
  };
  finalCta?: {
    headlinePrefix?: string;
    headlineAccent?: string;
    headlineSuffix?: string;
    headlineLine2?: string;
    subtitle?: string;
    ctaPrimary?: string;
    ctaSecondary?: string;
    tags?: Array<string>;
  };
  seo?: Seo;
};

export type PricingPage = {
  _id: string;
  _type: "pricingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  language?: string;
  faq?: {
    sectionLabel?: string;
    eyebrow?: string;
    title?: string;
    items?: Array<
      {
        _key: string;
      } & FaqItem
    >;
    footNote?: string;
    footLink?: string;
  };
  finalCta?: {
    sectionLabel?: string;
    headlinePrefix?: string;
    headlineAccent?: string;
    headlineSuffix?: string;
    headlineLine2?: string;
    subtitle?: string;
    ctaPrimary?: string;
    ctaSecondary?: string;
    socialProof?: string;
    tags?: Array<string>;
    trustPrefix?: string;
    trustBold?: string;
    trustSuffix?: string;
  };
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  language?: string;
  hero?: {
    sectionLabel?: string;
    badge?: string;
    headlinePrefix?: string;
    headlineAccent?: string;
    subtitle?: string;
    description?: string;
    ctaPrimary?: string;
    ctaSecondary?: string;
    trustTrial?: string;
    trustNoCard?: string;
    trustFreeClients?: string;
    calloutSkool?: string;
    calloutWhatsapp?: string;
    calloutTrainheroic?: string;
    productLabel?: string;
    productSubtext?: string;
    productImageAlt?: string;
    brandNote?: string;
  };
  features?: {
    ariaLabel?: string;
    eyebrow?: string;
    titlePrefix?: string;
    titleAccent?: string;
    titleSuffix?: string;
    tablistLabel?: string;
    cta?: string;
    tabs?: Array<
      {
        _key: string;
      } & FeatureTab
    >;
  };
  why?: {
    ariaLabel?: string;
    heading?: {
      line1?: string;
      line2?: string;
      line3?: string;
      accent?: string;
    };
    toggle?: {
      ariaLabel?: string;
      without?: string;
      with?: string;
    };
    desc?: {
      without?: string;
      with?: string;
    };
    bullets?: {
      without?: Array<string>;
      with?: Array<string>;
    };
    preview?: {
      without?: {
        card1?: {
          name?: string;
          desc?: string;
        };
        card2?: {
          name?: string;
          desc?: string;
        };
        card3?: {
          name?: string;
          desc?: string;
        };
        card4?: {
          name?: string;
          desc?: string;
        };
      };
      with?: {
        imgAlt?: string;
        appName?: string;
        appTagline?: string;
        syncedLabel?: string;
        modules?: Array<{
          label?: string;
          sub?: string;
          _key: string;
        }>;
      };
    };
  };
  steps?: {
    sectionLabel?: string;
    eyebrow?: string;
    titlePrefix?: string;
    titleAccent?: string;
    subtitle?: string;
    step1?: {
      title?: string;
      desc?: string;
    };
    step2?: {
      title?: string;
      desc?: string;
    };
    step3?: {
      title?: string;
      desc?: string;
    };
    cta?: string;
  };
  platform?: {
    ariaLabel?: string;
    eyebrow?: string;
    title?: string;
    subtitle?: string;
    navLabel?: string;
    steps?: Array<
      {
        _key: string;
      } & PlatformStep
    >;
  };
  tech?: {
    sectionLabel?: string;
    eyebrow?: string;
    headlineLead?: string;
    headlineAccent?: string;
    body?: string;
    tile1Title?: string;
    tile1Desc?: string;
    tile2Title?: string;
    tile2Desc?: string;
    tile3Title?: string;
    tile3Desc?: string;
    appStoreLabel?: string;
    appStoreSub?: string;
    appStoreMain?: string;
    playStoreLabel?: string;
    playStoreSub?: string;
    playStoreMain?: string;
    visualAlt?: string;
  };
  comparison?: {
    ariaLabel?: string;
    eyebrow?: string;
    title?: string;
    subtitle?: string;
    tableAriaLabel?: string;
    featureColumnLabel?: string;
    jimmyBadge?: string;
    competitors?: Array<string>;
    features?: Array<string>;
    footerLabel?: string;
  };
  pricing?: {
    sectionLabel?: string;
    promoBadge?: string;
    promoTextBold?: string;
    promoTextRest?: string;
    eyebrow?: string;
    title?: string;
    subtitle?: string;
    sliderQuestion?: string;
    sliderHelp?: string;
    currencyLabel?: string;
    sliderAriaLabel?: string;
    clients?: string;
    planFree?: string;
    planClub?: string;
    betaBadge?: string;
    perMonth?: string;
    forUpTo?: string;
    feesLabel?: string;
    feeSaveFree?: string;
    feeSaveClub?: string;
    ctaFree?: string;
    ctaClub?: string;
    lockNote?: string;
    whatsIncluded?: string;
    benefitsEyebrow?: string;
    benefits?: Array<{
      iconKey?:
        | "workout"
        | "messaging"
        | "app"
        | "payments"
        | "community"
        | "courses";
      text?: string;
      _type: "pricingBenefit";
      _key: string;
    }>;
    freeTag?: string;
    clubTag?: string;
    freePerLabel?: string;
    clubPerPrefix?: string;
    popularLabel?: string;
    freeFeatures?: Array<string>;
    clubFeatures?: Array<string>;
    addonsLabel?: string;
    addons?: Array<
      {
        _key: string;
      } & PricingAddon
    >;
  };
  beta?: {
    ariaLabel?: string;
    badge?: string;
    titleLine1?: string;
    titleLine2Prefix?: string;
    titleLine2Accent?: string;
    titleLine2Suffix?: string;
    body?: PortableTextBlock;
    card1?: {
      title?: string;
      desc?: string;
    };
    card2?: {
      title?: string;
      desc?: string;
    };
    card3?: {
      title?: string;
      desc?: string;
    };
  };
  team?: {
    sectionLabel?: string;
    eyebrow?: string;
    title?: string;
    subtitle?: string;
    members?: Array<
      {
        _key: string;
      } & TeamMember
    >;
    stats?: Array<
      {
        _key: string;
      } & TeamStat
    >;
  };
  faq?: {
    sectionLabel?: string;
    eyebrow?: string;
    title?: string;
    items?: Array<
      {
        _key: string;
      } & FaqItem
    >;
    footNote?: string;
    footLink?: string;
  };
  manifesto?: {
    sectionLabel?: string;
    label?: string;
    headlineLine1?: string;
    headlineLine2Prefix?: string;
    headlineLine2Accent?: string;
    headlineLine3?: string;
    body?: PortableTextBlock;
    mantraEmphasis?: string;
    mantraRest?: string;
  };
  finalCta?: {
    sectionLabel?: string;
    headlinePrefix?: string;
    headlineAccent?: string;
    headlineSuffix?: string;
    headlineLine2?: string;
    subtitle?: string;
    ctaPrimary?: string;
    ctaSecondary?: string;
    socialProof?: string;
    tags?: Array<string>;
    trustPrefix?: string;
    trustBold?: string;
    trustSuffix?: string;
  };
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Preview
  | RoadmapItem
  | SanityImageAssetReference
  | Guide
  | Seo
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Post
  | PricingFeatures
  | PricingFeaturesReference
  | Pricing
  | AffiliateSettings
  | PricingPlans
  | PlanFees
  | ChangelogChange
  | FeatureCap
  | GuideVideo
  | GuideFaq
  | GuideSteps
  | Checklist
  | GuideCallout
  | Pullquote
  | Callout
  | FaqItem
  | TeamStat
  | TeamMember
  | PricingAddon
  | PricingTier
  | PlatformStep
  | FeatureTab
  | PortableTextBlock
  | SocialLink
  | NavMegaItem
  | NavItem
  | TranslationMetadata
  | InternationalizedArrayReference
  | HomePageReference
  | PricingPageReference
  | AffiliatePageReference
  | NavigationReference
  | FooterReference
  | SiteSettingsReference
  | FeatureReference
  | ChangelogReleaseReference
  | InternationalizedArrayReferenceValue
  | ChangelogRelease
  | Feature
  | SiteSettings
  | Footer
  | Navigation
  | AffiliatePage
  | PricingPage
  | HomePage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/index.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && language == $locale][0]{    siteName,    siteDescription,    seo,    notFound  }
export type SITE_SETTINGS_QUERY_RESULT = {
  siteName: string | null;
  siteDescription: string | null;
  seo: Seo | null;
  notFound: {
    eyebrow?: string;
    title?: string;
    lead?: string;
    ctaPrimary?: string;
    ctaSecondary?: string;
  } | null;
} | null;

// Source: sanity/queries/index.ts
// Variable: PRICING_PAGE_QUERY
// Query: *[_type == "pricingPage" && language == $locale][0]{    title,    faq,    finalCta,    seo  }
export type PRICING_PAGE_QUERY_RESULT = {
  title: string | null;
  faq: {
    sectionLabel?: string;
    eyebrow?: string;
    title?: string;
    items?: Array<
      {
        _key: string;
      } & FaqItem
    >;
    footNote?: string;
    footLink?: string;
  } | null;
  finalCta: {
    sectionLabel?: string;
    headlinePrefix?: string;
    headlineAccent?: string;
    headlineSuffix?: string;
    headlineLine2?: string;
    subtitle?: string;
    ctaPrimary?: string;
    ctaSecondary?: string;
    socialProof?: string;
    tags?: Array<string>;
    trustPrefix?: string;
    trustBold?: string;
    trustSuffix?: string;
  } | null;
  seo: Seo | null;
} | null;

// Source: sanity/queries/index.ts
// Variable: PRICING_PLANS_QUERY
// Query: *[_type == "pricingPlans"][0]{    tiers[]{ clients, priceEur, priceUsd },    betaDiscountPct,    feesFree{ stripePctEur, stripePctUsd, stripeFixedEur, stripeFixedUsd, jimmyPct },    feesClub{ stripePctEur, stripePctUsd, stripeFixedEur, stripeFixedUsd, jimmyPct }  }
export type PRICING_PLANS_QUERY_RESULT = {
  tiers: Array<{
    clients: string | null;
    priceEur: number | null;
    priceUsd: number | null;
  }> | null;
  betaDiscountPct: number | null;
  feesFree: {
    stripePctEur: number | null;
    stripePctUsd: number | null;
    stripeFixedEur: number | null;
    stripeFixedUsd: number | null;
    jimmyPct: number | null;
  } | null;
  feesClub: {
    stripePctEur: number | null;
    stripePctUsd: number | null;
    stripeFixedEur: number | null;
    stripeFixedUsd: number | null;
    jimmyPct: number | null;
  } | null;
} | null;

// Source: sanity/queries/index.ts
// Variable: AFFILIATE_PAGE_QUERY
// Query: *[_type == "affiliatePage" && language == $locale][0]{    title,    hero,    calc,    how,    why,    who,    faq,    finalCta,    seo  }
export type AFFILIATE_PAGE_QUERY_RESULT = {
  title: string | null;
  hero: {
    socialProof?: string;
    eyebrow?: string;
    headlinePrefix?: string;
    headlineAccent?: string;
    headlineSuffix?: string;
    subtitle?: string;
    ctaPrimary?: string;
    ctaSecondary?: string;
  } | null;
  calc: {
    title?: string;
    helper?: string;
    coachesSuffix?: string;
    perMo?: string;
    estimateLabel?: string;
    recurringBadge?: string;
    monthlyLabel?: string;
    perYearTemplate?: string;
    basisLabel?: string;
    basisRangePrefix?: string;
    basisRangeSuffix?: string;
    footnote?: string;
    referralsLabel?: string;
    perMonthLabel?: string;
    perMonthTip?: string;
    perYearLabel?: string;
    perYearTip?: string;
    cta?: string;
    note?: string;
  } | null;
  how: {
    eyebrow?: string;
    title?: string;
    subtitle?: string;
    steps?: Array<{
      label?: string;
      name?: string;
      tagline?: string;
      _type: "step";
      _key: string;
    }>;
    labels?: {
      partnerBarTitle?: string;
      freeBadge?: string;
      accountName?: string;
      accountRole?: string;
      approved?: string;
      referralLinkLabel?: string;
      copy?: string;
      copied?: string;
      copiedToast?: string;
      tagsStep1?: Array<string>;
      shareBarTitle?: string;
      liveBadge?: string;
      linkClicksLabel?: string;
      clicksBadge?: string;
      channels?: Array<{
        name?: string;
        source?: string;
        _type: "channel";
        _key: string;
      }>;
      tagsStep2?: Array<string>;
      commissionsBarTitle?: string;
      monthBadge?: string;
      availableLabel?: string;
      withdraw?: string;
      newPaymentTemplate?: string;
      completed?: string;
      commissionTag?: string;
      tagsStep3?: Array<string>;
    };
  } | null;
  why: {
    eyebrow?: string;
    title?: string;
    cards?: Array<{
      title?: string;
      body?: string;
      _type: "card";
      _key: string;
    }>;
  } | null;
  who: {
    title?: string;
    subtitle?: string;
    items?: Array<{
      title?: string;
      sub?: string;
      _type: "item";
      _key: string;
    }>;
  } | null;
  faq: {
    eyebrow?: string;
    title?: string;
    items?: Array<
      {
        _key: string;
      } & FaqItem
    >;
    footNote?: string;
    footLink?: string;
  } | null;
  finalCta: {
    headlinePrefix?: string;
    headlineAccent?: string;
    headlineSuffix?: string;
    headlineLine2?: string;
    subtitle?: string;
    ctaPrimary?: string;
    ctaSecondary?: string;
    tags?: Array<string>;
  } | null;
  seo: Seo | null;
} | null;

// Source: sanity/queries/index.ts
// Variable: AFFILIATE_SETTINGS_QUERY
// Query: *[_type == "affiliateSettings"][0]{    rate, sliderMin, sliderMax, sliderDefault, ticks,    eur{ avg, lo, hi },    usd{ avg, lo, hi }  }
export type AFFILIATE_SETTINGS_QUERY_RESULT = {
  rate: number | null;
  sliderMin: number | null;
  sliderMax: number | null;
  sliderDefault: number | null;
  ticks: Array<number> | null;
  eur: {
    avg: number | null;
    lo: number | null;
    hi: number | null;
  } | null;
  usd: {
    avg: number | null;
    lo: number | null;
    hi: number | null;
  } | null;
} | null;

// Source: sanity/queries/index.ts
// Variable: HOME_QUERY
// Query: *[_type == "homePage" && language == $locale][0]{    title,    hero,    features,    why,    steps,    platform,    tech,    comparison,    pricing,    beta,    team,    faq,    manifesto,    finalCta,    seo  }
export type HOME_QUERY_RESULT = {
  title: string | null;
  hero: {
    sectionLabel?: string;
    badge?: string;
    headlinePrefix?: string;
    headlineAccent?: string;
    subtitle?: string;
    description?: string;
    ctaPrimary?: string;
    ctaSecondary?: string;
    trustTrial?: string;
    trustNoCard?: string;
    trustFreeClients?: string;
    calloutSkool?: string;
    calloutWhatsapp?: string;
    calloutTrainheroic?: string;
    productLabel?: string;
    productSubtext?: string;
    productImageAlt?: string;
    brandNote?: string;
  } | null;
  features: {
    ariaLabel?: string;
    eyebrow?: string;
    titlePrefix?: string;
    titleAccent?: string;
    titleSuffix?: string;
    tablistLabel?: string;
    cta?: string;
    tabs?: Array<
      {
        _key: string;
      } & FeatureTab
    >;
  } | null;
  why: {
    ariaLabel?: string;
    heading?: {
      line1?: string;
      line2?: string;
      line3?: string;
      accent?: string;
    };
    toggle?: {
      ariaLabel?: string;
      without?: string;
      with?: string;
    };
    desc?: {
      without?: string;
      with?: string;
    };
    bullets?: {
      without?: Array<string>;
      with?: Array<string>;
    };
    preview?: {
      without?: {
        card1?: {
          name?: string;
          desc?: string;
        };
        card2?: {
          name?: string;
          desc?: string;
        };
        card3?: {
          name?: string;
          desc?: string;
        };
        card4?: {
          name?: string;
          desc?: string;
        };
      };
      with?: {
        imgAlt?: string;
        appName?: string;
        appTagline?: string;
        syncedLabel?: string;
        modules?: Array<{
          label?: string;
          sub?: string;
          _key: string;
        }>;
      };
    };
  } | null;
  steps: {
    sectionLabel?: string;
    eyebrow?: string;
    titlePrefix?: string;
    titleAccent?: string;
    subtitle?: string;
    step1?: {
      title?: string;
      desc?: string;
    };
    step2?: {
      title?: string;
      desc?: string;
    };
    step3?: {
      title?: string;
      desc?: string;
    };
    cta?: string;
  } | null;
  platform: {
    ariaLabel?: string;
    eyebrow?: string;
    title?: string;
    subtitle?: string;
    navLabel?: string;
    steps?: Array<
      {
        _key: string;
      } & PlatformStep
    >;
  } | null;
  tech: {
    sectionLabel?: string;
    eyebrow?: string;
    headlineLead?: string;
    headlineAccent?: string;
    body?: string;
    tile1Title?: string;
    tile1Desc?: string;
    tile2Title?: string;
    tile2Desc?: string;
    tile3Title?: string;
    tile3Desc?: string;
    appStoreLabel?: string;
    appStoreSub?: string;
    appStoreMain?: string;
    playStoreLabel?: string;
    playStoreSub?: string;
    playStoreMain?: string;
    visualAlt?: string;
  } | null;
  comparison: {
    ariaLabel?: string;
    eyebrow?: string;
    title?: string;
    subtitle?: string;
    tableAriaLabel?: string;
    featureColumnLabel?: string;
    jimmyBadge?: string;
    competitors?: Array<string>;
    features?: Array<string>;
    footerLabel?: string;
  } | null;
  pricing: {
    sectionLabel?: string;
    promoBadge?: string;
    promoTextBold?: string;
    promoTextRest?: string;
    eyebrow?: string;
    title?: string;
    subtitle?: string;
    sliderQuestion?: string;
    sliderHelp?: string;
    currencyLabel?: string;
    sliderAriaLabel?: string;
    clients?: string;
    planFree?: string;
    planClub?: string;
    betaBadge?: string;
    perMonth?: string;
    forUpTo?: string;
    feesLabel?: string;
    feeSaveFree?: string;
    feeSaveClub?: string;
    ctaFree?: string;
    ctaClub?: string;
    lockNote?: string;
    whatsIncluded?: string;
    benefitsEyebrow?: string;
    benefits?: Array<{
      iconKey?:
        | "app"
        | "community"
        | "courses"
        | "messaging"
        | "payments"
        | "workout";
      text?: string;
      _type: "pricingBenefit";
      _key: string;
    }>;
    freeTag?: string;
    clubTag?: string;
    freePerLabel?: string;
    clubPerPrefix?: string;
    popularLabel?: string;
    freeFeatures?: Array<string>;
    clubFeatures?: Array<string>;
    addonsLabel?: string;
    addons?: Array<
      {
        _key: string;
      } & PricingAddon
    >;
  } | null;
  beta: {
    ariaLabel?: string;
    badge?: string;
    titleLine1?: string;
    titleLine2Prefix?: string;
    titleLine2Accent?: string;
    titleLine2Suffix?: string;
    body?: PortableTextBlock;
    card1?: {
      title?: string;
      desc?: string;
    };
    card2?: {
      title?: string;
      desc?: string;
    };
    card3?: {
      title?: string;
      desc?: string;
    };
  } | null;
  team: {
    sectionLabel?: string;
    eyebrow?: string;
    title?: string;
    subtitle?: string;
    members?: Array<
      {
        _key: string;
      } & TeamMember
    >;
    stats?: Array<
      {
        _key: string;
      } & TeamStat
    >;
  } | null;
  faq: {
    sectionLabel?: string;
    eyebrow?: string;
    title?: string;
    items?: Array<
      {
        _key: string;
      } & FaqItem
    >;
    footNote?: string;
    footLink?: string;
  } | null;
  manifesto: {
    sectionLabel?: string;
    label?: string;
    headlineLine1?: string;
    headlineLine2Prefix?: string;
    headlineLine2Accent?: string;
    headlineLine3?: string;
    body?: PortableTextBlock;
    mantraEmphasis?: string;
    mantraRest?: string;
  } | null;
  finalCta: {
    sectionLabel?: string;
    headlinePrefix?: string;
    headlineAccent?: string;
    headlineSuffix?: string;
    headlineLine2?: string;
    subtitle?: string;
    ctaPrimary?: string;
    ctaSecondary?: string;
    socialProof?: string;
    tags?: Array<string>;
    trustPrefix?: string;
    trustBold?: string;
    trustSuffix?: string;
  } | null;
  seo: Seo | null;
} | null;

// Source: sanity/queries/index.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation" && language == $locale][0]{    featuresLabel,    featuresForCoaches,    featuresForMembers,    featuresItems[]{ key, title, subtitle, href },    featuresCta,    resourcesLabel,    resourcesContent,    resourcesCommunity,    resourcesItems[]{ key, title, subtitle, href },    pricing,    affiliate,    newBadge,    login,    getStarted,    getStartedShort,    openMenu,    close,    menu  }
export type NAVIGATION_QUERY_RESULT = {
  featuresLabel: string | null;
  featuresForCoaches: string | null;
  featuresForMembers: string | null;
  featuresItems: Array<{
    key: string | null;
    title: string | null;
    subtitle: string | null;
    href: string | null;
  }> | null;
  featuresCta: {
    label?: string;
    title?: string;
    body?: string;
    btn?: string;
  } | null;
  resourcesLabel: string | null;
  resourcesContent: string | null;
  resourcesCommunity: string | null;
  resourcesItems: Array<{
    key: string | null;
    title: string | null;
    subtitle: string | null;
    href: string | null;
  }> | null;
  pricing: string | null;
  affiliate: string | null;
  newBadge: string | null;
  login: string | null;
  getStarted: string | null;
  getStartedShort: string | null;
  openMenu: string | null;
  close: string | null;
  menu: string | null;
} | null;

// Source: sanity/queries/index.ts
// Variable: FOOTER_QUERY
// Query: *[_type == "footer" && language == $locale][0]{    taglinePrefix,    taglineEmphasis,    productHeading,    productLinks[]{ label, href, external },    companyHeading,    companyLinks[]{ label, href, external },    legalHeading,    legalLinks[]{ label, href, external },    copy  }
export type FOOTER_QUERY_RESULT = {
  taglinePrefix: string | null;
  taglineEmphasis: string | null;
  productHeading: string | null;
  productLinks: Array<{
    label: string | null;
    href: string | null;
    external: boolean | null;
  }> | null;
  companyHeading: string | null;
  companyLinks: Array<{
    label: string | null;
    href: string | null;
    external: boolean | null;
  }> | null;
  legalHeading: string | null;
  legalLinks: Array<{
    label: string | null;
    href: string | null;
    external: boolean | null;
  }> | null;
  copy: string | null;
} | null;

// Source: sanity/queries/index.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]|order(publishedAt desc){      "slug": slug.current,  category,  title,  excerpt,  publishedAt,  readMin,  featured,  pick,  coverImage  }
export type POSTS_QUERY_RESULT = Array<{
  slug: string | null;
  category:
    | "business"
    | "product"
    | "retention"
    | "stories"
    | "training"
    | null;
  title: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  readMin: number | null;
  featured: boolean | null;
  pick: boolean | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: sanity/queries/index.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{      "slug": slug.current,  category,  title,  excerpt,  publishedAt,  readMin,  featured,  pick,  coverImage,    lead,    coverImage{ ..., alt },    body[]{      ...,      _type == "image" => { ..., asset, alt, caption }    }  }
export type POST_QUERY_RESULT = {
  slug: string | null;
  category:
    | "business"
    | "product"
    | "retention"
    | "stories"
    | "training"
    | null;
  title: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  readMin: number | null;
  featured: boolean | null;
  pick: boolean | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  lead: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "callout";
        tone?: "check" | "spark";
        label?: string;
        text?: string;
      }
    | {
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string | null;
        caption: string | null;
        _type: "image";
        _key: string;
      }
    | {
        _key: string;
        _type: "pullquote";
        text?: string;
        cite?: string;
      }
  > | null;
} | null;

// Source: sanity/queries/index.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: sanity/queries/index.ts
// Variable: GUIDES_QUERY
// Query: *[_type == "guide" && defined(slug.current)] | order(category asc, order asc){      "slug": slug.current,  category,  title,  lead,  level,  readMin,  updatedAt,  popular,  order  }
export type GUIDES_QUERY_RESULT = Array<{
  slug: string | null;
  category:
    | "branded-app"
    | "community"
    | "getting-started"
    | "payments"
    | "programming"
    | "retention"
    | null;
  title: string | null;
  lead: string | null;
  level: "Advanced" | "Beginner" | "Intermediate" | null;
  readMin: number | null;
  updatedAt: string | null;
  popular: boolean | null;
  order: number | null;
}>;

// Source: sanity/queries/index.ts
// Variable: GUIDE_QUERY
// Query: *[_type == "guide" && slug.current == $slug][0]{      "slug": slug.current,  category,  title,  lead,  level,  readMin,  updatedAt,  popular,  order,    seo,    body[]{      ...,      _type == "image" => { ..., asset, alt, caption },      _type == "guideSteps" => {        ...,        items[]{          title,          body[]{            ...,            _type == "image" => { ..., asset, alt, caption }          }        }      }    }  }
export type GUIDE_QUERY_RESULT = {
  slug: string | null;
  category:
    | "branded-app"
    | "community"
    | "getting-started"
    | "payments"
    | "programming"
    | "retention"
    | null;
  title: string | null;
  lead: string | null;
  level: "Advanced" | "Beginner" | "Intermediate" | null;
  readMin: number | null;
  updatedAt: string | null;
  popular: boolean | null;
  order: number | null;
  seo: Seo | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "checklist";
        items?: Array<string>;
      }
    | {
        _key: string;
        _type: "guideCallout";
        tone?: "note" | "success" | "tip" | "warn";
        label?: string;
        text?: string;
      }
    | {
        _key: string;
        _type: "guideFaq";
        items?: Array<{
          q?: string;
          a?: string;
          _type: "guideFaqItem";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "guideSteps";
        items: Array<{
          title: string | null;
          body: Array<
            | {
                children?: Array<{
                  marks?: Array<string>;
                  text?: string;
                  _type: "span";
                  _key: string;
                }>;
                style?: "h3" | "normal";
                listItem?: "bullet";
                markDefs?: Array<{
                  href?: string;
                  _type: "link";
                  _key: string;
                }>;
                level?: number;
                _type: "block";
                _key: string;
              }
            | {
                _key: string;
                _type: "guideCallout";
                tone?: "note" | "success" | "tip" | "warn";
                label?: string;
                text?: string;
              }
            | {
                asset: SanityImageAssetReference | null;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                alt: string | null;
                caption: string | null;
                _type: "image";
                _key: string;
              }
          > | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "guideVideo";
        label?: string;
        duration?: string;
        url?: string;
      }
    | {
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string | null;
        caption: string | null;
        _type: "image";
        _key: string;
      }
  > | null;
} | null;

// Source: sanity/queries/index.ts
// Variable: GUIDE_SLUGS_QUERY
// Query: *[_type == "guide" && defined(slug.current)]{ "slug": slug.current }
export type GUIDE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: sanity/queries/index.ts
// Variable: FEATURES_QUERY
// Query: *[_type == "feature" && defined(slug.current) && language == $locale] | order(order asc){      "slug": slug.current,  audience,  name,  sub,  iconKey,  order  }
export type FEATURES_QUERY_RESULT = Array<{
  slug: string | null;
  audience: "For Coaches" | "For Members" | null;
  name: string | null;
  sub: string | null;
  iconKey: string | null;
  order: number | null;
}>;

// Source: sanity/queries/index.ts
// Variable: FEATURE_QUERY
// Query: *[_type == "feature" && slug.current == $slug && language == $locale][0]{      "slug": slug.current,  audience,  name,  sub,  iconKey,  order,    demoKey,    title{ prefix, accent, suffix },    highlight{ prefix, accent },    highlightSub,    lead,    tags,    capsTitle,    caps[]{ iconKey, title, desc },    seo  }
export type FEATURE_QUERY_RESULT = {
  slug: string | null;
  audience: "For Coaches" | "For Members" | null;
  name: string | null;
  sub: string | null;
  iconKey: string | null;
  order: number | null;
  demoKey: string | null;
  title: {
    prefix: string | null;
    accent: string | null;
    suffix: string | null;
  } | null;
  highlight: {
    prefix: string | null;
    accent: string | null;
  } | null;
  highlightSub: string | null;
  lead: string | null;
  tags: Array<string> | null;
  capsTitle: string | null;
  caps: Array<{
    iconKey: string | null;
    title: string | null;
    desc: string | null;
  }> | null;
  seo: Seo | null;
} | null;

// Source: sanity/queries/index.ts
// Variable: FEATURE_SLUGS_QUERY
// Query: *[_type == "feature" && defined(slug.current) && language == "en"]{ "slug": slug.current }
export type FEATURE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: sanity/queries/index.ts
// Variable: CHANGELOG_QUERY
// Query: *[_type == "changelogRelease" && defined(date) && language == $locale] | order(date desc){    version,    date,    title,    lead,    image{ ..., alt },    changes[]{ type, text }  }
export type CHANGELOG_QUERY_RESULT = Array<{
  version: string | null;
  date: string | null;
  title: string | null;
  lead: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: "image";
  } | null;
  changes: Array<{
    type: "fixed" | "improved" | "new" | null;
    text: string | null;
  }> | null;
}>;

// Source: sanity/queries/index.ts
// Variable: ROADMAP_QUERY
// Query: *[_type == "roadmapItem"] | order(order asc){    "id": _id,    column,    category,    title,    desc,    eta,    votes  }
export type ROADMAP_QUERY_RESULT = Array<{
  id: string;
  column: "later" | "next" | "now" | null;
  category: "app" | "coach" | "community" | "payments" | "training" | null;
  title: string | null;
  desc: string | null;
  eta: string | null;
  votes: number | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings" && language == $locale][0]{\n    siteName,\n    siteDescription,\n    seo,\n    notFound\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "pricingPage" && language == $locale][0]{\n    title,\n    faq,\n    finalCta,\n    seo\n  }\n': PRICING_PAGE_QUERY_RESULT;
    '\n  *[_type == "pricingPlans"][0]{\n    tiers[]{ clients, priceEur, priceUsd },\n    betaDiscountPct,\n    feesFree{ stripePctEur, stripePctUsd, stripeFixedEur, stripeFixedUsd, jimmyPct },\n    feesClub{ stripePctEur, stripePctUsd, stripeFixedEur, stripeFixedUsd, jimmyPct }\n  }\n': PRICING_PLANS_QUERY_RESULT;
    '\n  *[_type == "affiliatePage" && language == $locale][0]{\n    title,\n    hero,\n    calc,\n    how,\n    why,\n    who,\n    faq,\n    finalCta,\n    seo\n  }\n': AFFILIATE_PAGE_QUERY_RESULT;
    '\n  *[_type == "affiliateSettings"][0]{\n    rate, sliderMin, sliderMax, sliderDefault, ticks,\n    eur{ avg, lo, hi },\n    usd{ avg, lo, hi }\n  }\n': AFFILIATE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "homePage" && language == $locale][0]{\n    title,\n    hero,\n    features,\n    why,\n    steps,\n    platform,\n    tech,\n    comparison,\n    pricing,\n    beta,\n    team,\n    faq,\n    manifesto,\n    finalCta,\n    seo\n  }\n': HOME_QUERY_RESULT;
    '\n  *[_type == "navigation" && language == $locale][0]{\n    featuresLabel,\n    featuresForCoaches,\n    featuresForMembers,\n    featuresItems[]{ key, title, subtitle, href },\n    featuresCta,\n    resourcesLabel,\n    resourcesContent,\n    resourcesCommunity,\n    resourcesItems[]{ key, title, subtitle, href },\n    pricing,\n    affiliate,\n    newBadge,\n    login,\n    getStarted,\n    getStartedShort,\n    openMenu,\n    close,\n    menu\n  }\n': NAVIGATION_QUERY_RESULT;
    '\n  *[_type == "footer" && language == $locale][0]{\n    taglinePrefix,\n    taglineEmphasis,\n    productHeading,\n    productLinks[]{ label, href, external },\n    companyHeading,\n    companyLinks[]{ label, href, external },\n    legalHeading,\n    legalLinks[]{ label, href, external },\n    copy\n  }\n': FOOTER_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]|order(publishedAt desc){\n    \n  "slug": slug.current,\n  category,\n  title,\n  excerpt,\n  publishedAt,\n  readMin,\n  featured,\n  pick,\n  coverImage\n\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    \n  "slug": slug.current,\n  category,\n  title,\n  excerpt,\n  publishedAt,\n  readMin,\n  featured,\n  pick,\n  coverImage\n,\n    lead,\n    coverImage{ ..., alt },\n    body[]{\n      ...,\n      _type == "image" => { ..., asset, alt, caption }\n    }\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]{ "slug": slug.current }\n': POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "guide" && defined(slug.current)] | order(category asc, order asc){\n    \n  "slug": slug.current,\n  category,\n  title,\n  lead,\n  level,\n  readMin,\n  updatedAt,\n  popular,\n  order\n\n  }\n': GUIDES_QUERY_RESULT;
    '\n  *[_type == "guide" && slug.current == $slug][0]{\n    \n  "slug": slug.current,\n  category,\n  title,\n  lead,\n  level,\n  readMin,\n  updatedAt,\n  popular,\n  order\n,\n    seo,\n    body[]{\n      ...,\n      _type == "image" => { ..., asset, alt, caption },\n      _type == "guideSteps" => {\n        ...,\n        items[]{\n          title,\n          body[]{\n            ...,\n            _type == "image" => { ..., asset, alt, caption }\n          }\n        }\n      }\n    }\n  }\n': GUIDE_QUERY_RESULT;
    '\n  *[_type == "guide" && defined(slug.current)]{ "slug": slug.current }\n': GUIDE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "feature" && defined(slug.current) && language == $locale] | order(order asc){\n    \n  "slug": slug.current,\n  audience,\n  name,\n  sub,\n  iconKey,\n  order\n\n  }\n': FEATURES_QUERY_RESULT;
    '\n  *[_type == "feature" && slug.current == $slug && language == $locale][0]{\n    \n  "slug": slug.current,\n  audience,\n  name,\n  sub,\n  iconKey,\n  order\n,\n    demoKey,\n    title{ prefix, accent, suffix },\n    highlight{ prefix, accent },\n    highlightSub,\n    lead,\n    tags,\n    capsTitle,\n    caps[]{ iconKey, title, desc },\n    seo\n  }\n': FEATURE_QUERY_RESULT;
    '\n  *[_type == "feature" && defined(slug.current) && language == "en"]{ "slug": slug.current }\n': FEATURE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "changelogRelease" && defined(date) && language == $locale] | order(date desc){\n    version,\n    date,\n    title,\n    lead,\n    image{ ..., alt },\n    changes[]{ type, text }\n  }\n': CHANGELOG_QUERY_RESULT;
    '\n  *[_type == "roadmapItem"] | order(order asc){\n    "id": _id,\n    column,\n    category,\n    title,\n    desc,\n    eta,\n    votes\n  }\n': ROADMAP_QUERY_RESULT;
  }
}
